@host = https://localhost
@port = 7295
@token = CfDJ8JWRgDF-IUFOr3yf65Vqxgjm7yiKg7Z5JaG7fJMueNtVIXN_0SPpbdLmI8oKWWfwyNCHsANudvn_cWV2v90yrGtISU37voprVWSE3-WkSCdpWDvEJDXWPEAe4fcw6IuLtNL-CAN2cfHpkfKz5BI7pOjUsNnfORxyxdvz8ALYFOX_IJyHbSjyAraC64Ib5l0JI-K_ORk90oR1CKwXQrJCXg033D8iNwmluJ4B9IkEL9v56DDnvrAufyQaia91Avka4tMrKjo-d2DaXM0Kmkg_qybqCufaANj0xc5wD0feLVVDdXp5ifO74XKPbDf1Co4AoWstaBNyipB1ABYPhJx_iMlZDEn3PXdhSjY7Wv5DsjuecFcFhIbBnN8764MfMourqzwX2vXgcWjEPl3nf8Vde2VhzTtIT_zlqZzzlnZsBVpic43dRSbCbr5n5lCnGoIwI6-FrPYIW0SeWdOhBUsjNE5gHXzhHbJmgx7vcCHj39h5jmyR3c17TFJwJibpXnYyULVnMl_qOh5qnje1MWrTZDVXlcvwI0QHOOzYVjp-77gqDJW9BxEEyJiENWMpMWFuAIQv5zJO520NVFVzVlXZX6Y3yM8dxlnl7kj9uQknILS7hG1pg6QCjtMRAI87ndZ_4JQl9FhmFknI2Wf3qyUHZKsi8P6HisMxGORTpRRjC34ZfTqRYBkRPd6L4-MyBr2q_UtlQhak1oQXYU_6bIpc4m0ir7LYgUQ4WCw_5oIaVev-7JCzSLy4VK9_O63qykKEpc_COh8g27cVxvSjgq5cj1mnCyBJPjwobn0cB_HLvFpP

@Restaurant_API_Address= {{host}}:{{port}}

GET {{Restaurant_API_Address}}/api/restaurants
Authorization: Bearer {{token}}
Accept: application/json

###
  
GET {{Restaurant_API_Address}}/api/restaurants/bf6fde4f-7cfb-4505-5b97-08dca220c734
Accept: application/json

###

POST {{Restaurant_API_Address}}/api/restaurants/create
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "Name": "Viva Mexico",
    "Description": "Delisious breakfast for everyonoe",
    "Category": "Mexican",
    "HasDelivery": true,
    "ContactEmail": "contact@samplerestaurant.com",
    "ContactNumber": "123-456-7890",
    "City": "Sample City",
    "Street": "123 Sample Street",
    "PostalCode": "12345"
}


###

POST {{Restaurant_API_Address}}/api/restaurants/create
Content-Type: application/json

{

}

###

DELETE {{Restaurant_API_Address}}/api/restaurants/88ac48f4-2e6a-4896-d22b-08dca2201345

###

PUT {{Restaurant_API_Address}}/api/restaurants
Content-Type: application/json

{
    "Guid": "994f6bdc-872a-452e-003b-08dca2dcee2b",
    "Name": "Joia",
    "Description": "Elegant restaurant for the entire family",
    "Category": "Mexican",
    "HasDelivery": true,
    "ContactEmail": "contact@samplerestaurant.com",
    "ContactNumber": "123-456-7890",
    "City": "Sample City",
    "Street": "123 Sample Street",
    "PostalCode": "12345"
}

###

POST {{Restaurant_API_Address}}/api/restaurants/bf6fde4f-7cfb-4505-5b97-08dca220c734/dishes
Content-Type: application/json

{
  "name": "Taco de tripas",
  "description": "Puede ser doradita o blandita",
  "price": 25,
  "kiloCalories": 300
}

###

GET {{Restaurant_API_Address}}/api/restaurants/bf6fde4f-7cfb-4505-5b97-08dca220c734/dishes

###

DELETE {{Restaurant_API_Address}}/api/restarurants/bf6fde4f-7cfb-4505-5b97-08dca220c734/dishes/7

###

DELETE {{Restaurant_API_Address}}/api/restaurants/bf6fde4f-7cfb-4505-5b97-08dca220c734/dishes/8

###
POST {{Restaurant_API_Address}}/api/identity/register
Content-Type: application/json

{
  "email": "owner@gmail.com",
  "password": "Donadona21."
}

###
POST {{Restaurant_API_Address}}/api/identity/login
Content-Type: application/json

{
  "email": "admin@gmail.com",
  "password": "Donadona21."
}

###

POST {{Restaurant_API_Address}}/api/identity/userRole
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "userEmail" : "temo@gmail.com",
  "RoleName" : "owner"
}
