@host = https://localhost
@port = 7295

@Restaurant_API_Address= {{host}}:{{port}}

GET {{Restaurant_API_Address}}/api/restaurants
Accept: application/json

###
  
GET {{Restaurant_API_Address}}/api/restaurants/ae71aed5-b257-4cda-5b96-08dca220c735
Accept: application/json

###

POST {{Restaurant_API_Address}}/api/restaurants/create
Content-Type: application/json

{
    "Name": "Canela Desayunos",
    "Description": "Delisious breakfast for everyonoe",
    "Category": "Mexican",
    "HasDelivery": true,
    "ContactEmail": "contact@samplerestaurant.com",
    "ContactNumber": "123-456-7890",
    "City": "Sample City",
    "Street": "123 Sample Street",
    "PostalCode": "12345"
}


###

POST {{Restaurant_API_Address}}/api/restaurants/create
Content-Type: application/json

{

}

###

DELETE {{Restaurant_API_Address}}/api/restaurants/88ac48f4-2e6a-4896-d22b-08dca2201345

###

PUT {{Restaurant_API_Address}}/api/restaurants
Content-Type: application/json

{
    "Guid": "994f6bdc-872a-452e-003b-08dca2dcee2b",
    "Name": "Joia",
    "Description": "Elegant restaurant for the entire family",
    "Category": "Mexican",
    "HasDelivery": true,
    "ContactEmail": "contact@samplerestaurant.com",
    "ContactNumber": "123-456-7890",
    "City": "Sample City",
    "Street": "123 Sample Street",
    "PostalCode": "12345"
}

